## Ahmad 2610-4004

## Assignment : Lab 2 

## Class : Machine Learning Lab


___

## Part 1 Pandas tasks 

In [1]:
import pandas as pd

In [2]:
#import dataset
df = pd.read_csv("churn.csv")

___
#### TASK 1
Find out the head of this dataset in transpose mode.

In [3]:
df.head().transpose()

0             1               2  \
customerID              7590-VHVEG    5575-GNVDE      3668-QPYBK   
gender                      Female          Male            Male   
SeniorCitizen                    0             0               0   
Partner                        Yes            No              No   
Dependents                      No            No              No   
tenure                           1            34               2   
PhoneService                    No           Yes             Yes   
MultipleLines     No phone service            No              No   
InternetService                DSL           DSL             DSL   
OnlineSecurity                  No           Yes             Yes   
OnlineBackup                   Yes            No             Yes   
DeviceProtection                No           Yes              No   
TechSupport                     No            No              No   
StreamingTV                     No            No              No   
StreamingMovies                 No            No              No   
Contract            Month-to-month      One year  Month-to-month   
PaperlessBilling               Yes            No             Yes   
PaymentMethod     Electronic check  Mailed check    Mailed check   
MonthlyCharges               29.85         56.95           53.85   
TotalCharges                 29.85        1889.5          108.15   
Churn                           No            No             Yes   

                                          3                 4  
customerID                       7795-CFOCW        9237-HQITU  
gender                                 Male            Female  
SeniorCitizen                             0                 0  
Partner                                  No                No  
Dependents                               No                No  
tenure                                   45                 2  
PhoneService                             No               Yes  
MultipleLines              No phone service                No  
InternetService                         DSL       Fiber optic  
OnlineSecurity                          Yes                No  
OnlineBackup                             No                No  
DeviceProtection                        Yes                No  
TechSupport                             Yes                No  
StreamingTV                              No                No  
StreamingMovies                          No                No  
Contract                           One year    Month-to-month  
PaperlessBilling                         No               Yes  
PaymentMethod     Bank transfer (automatic)  Electronic check  
MonthlyCharges                         42.3              70.7  
TotalCharges                        1840.75            151.65  
Churn                                    No               Yes

___
#### TASK 2
Find the tail of this dataset in transpose mode


In [4]:
df.tail().transpose()

7038                     7039              7040  \
customerID          6840-RESVB               2234-XADUH        4801-JZAZL   
gender                    Male                   Female            Female   
SeniorCitizen                0                        0                 0   
Partner                    Yes                      Yes               Yes   
Dependents                 Yes                      Yes               Yes   
tenure                      24                       72                11   
PhoneService               Yes                      Yes                No   
MultipleLines              Yes                      Yes  No phone service   
InternetService            DSL              Fiber optic               DSL   
OnlineSecurity             Yes                       No               Yes   
OnlineBackup                No                      Yes                No   
DeviceProtection           Yes                      Yes                No   
TechSupport                Yes                       No                No   
StreamingTV                Yes                      Yes                No   
StreamingMovies            Yes                      Yes                No   
Contract              One year                 One year    Month-to-month   
PaperlessBilling           Yes                      Yes               Yes   
PaymentMethod     Mailed check  Credit card (automatic)  Electronic check   
MonthlyCharges            84.8                    103.2              29.6   
TotalCharges            1990.5                   7362.9            346.45   
Churn                       No                       No                No   

                            7041                       7042  
customerID            8361-LTMKD                 3186-AJIEK  
gender                      Male                       Male  
SeniorCitizen                  1                          0  
Partner                      Yes                         No  
Dependents                    No                         No  
tenure                         4                         66  
PhoneService                 Yes                        Yes  
MultipleLines                Yes                         No  
InternetService      Fiber optic                Fiber optic  
OnlineSecurity                No                        Yes  
OnlineBackup                  No                         No  
DeviceProtection              No                        Yes  
TechSupport                   No                        Yes  
StreamingTV                   No                        Yes  
StreamingMovies               No                        Yes  
Contract          Month-to-month                   Two year  
PaperlessBilling             Yes                        Yes  
PaymentMethod       Mailed check  Bank transfer (automatic)  
MonthlyCharges              74.4                     105.65  
TotalCharges               306.6                     6844.5  
Churn                        Yes                         No

____
#### TASK 3

show 10 random entries from dataset

In [5]:
df.sample(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
2092  2251-PYLPB    Male              0     Yes         No      72   
1414  5302-BDJNT    Male              0      No         No      35   
565   5846-NEQVZ    Male              0     Yes        Yes      71   
37    6572-ADKRS  Female              0      No         No      46   
4627  3680-CTHUH    Male              0      No         No      60   
5449  5696-CEIQJ    Male              0     Yes        Yes      67   
1522  5766-XQXMQ  Female              0      No         No      29   
6778  5893-KCLGT  Female              0      No        Yes      72   
5150  7017-VFULY  Female              0     Yes         No       2   
2009  7639-OPLNG    Male              0     Yes        Yes      70   

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
2092          Yes           Yes             DSL                  Yes  ...   
1414          Yes           Yes     Fiber optic                   No  ...   
565           Yes            No             DSL                  Yes  ...   
37            Yes            No     Fiber optic                   No  ...   
4627          Yes           Yes     Fiber optic                  Yes  ...   
5449          Yes            No     Fiber optic                   No  ...   
1522          Yes            No             DSL                  Yes  ...   
6778          Yes            No              No  No internet service  ...   
5150          Yes            No              No  No internet service  ...   
2009          Yes           Yes             DSL                  Yes  ...   

         DeviceProtection          TechSupport          StreamingTV  \
2092                  Yes                  Yes                   No   
1414                  Yes                  Yes                  Yes   
565                   Yes                  Yes                   No   
37                    Yes                   No                   No   
4627                  Yes                  Yes                  Yes   
5449                  Yes                  Yes                  Yes   
1522                  Yes                   No                   No   
6778  No internet service  No internet service  No internet service   
5150  No internet service  No internet service  No internet service   
2009                  Yes                  Yes                  Yes   

          StreamingMovies        Contract PaperlessBilling  \
2092                  Yes        Two year               No   
1414                   No  Month-to-month               No   
565                   Yes        Two year              Yes   
37                     No  Month-to-month              Yes   
4627                  Yes        One year              Yes   
5449                  Yes        Two year               No   
1522                  Yes  Month-to-month              Yes   
6778  No internet service        Two year              Yes   
5150  No internet service  Month-to-month               No   
2009                   No        Two year              Yes   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
2092    Credit card (automatic)          79.55        5810.9    No  
1414           Electronic check          95.50        3418.2    No  
565     Credit card (automatic)          70.85        4973.4    No  
37      Credit card (automatic)          74.80        3548.3    No  
4627    Credit card (automatic)         116.60        7049.5    No  
5449  Bank transfer (automatic)         103.15        6895.5    No  
1522  Bank transfer (automatic)          68.85        1970.5   Yes  
6778               Mailed check          19.75          1567    No  
5150  Bank transfer (automatic)          20.10         43.15    No  
2009  Bank transfer (automatic)          79.25       5731.85    No  

[10 rows x 21 columns]

____
#### TASK 4
show the shape of this dataset and also columns


In [6]:
print(df.shape)


(7043, 21)


In [7]:
for column in df.columns:
    print(f"{column} ")

customerID 
gender 
SeniorCitizen 
Partner 
Dependents 
tenure 
PhoneService 
MultipleLines 
InternetService 
OnlineSecurity 
OnlineBackup 
DeviceProtection 
TechSupport 
StreamingTV 
StreamingMovies 
Contract 
PaperlessBilling 
PaymentMethod 
MonthlyCharges 
TotalCharges 
Churn 


In [8]:
df.TotalCharges

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...   
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: str

___
#### TASK 5

In this dataset, there is a column called “TotalCharges”. Find out the sum of the total charges. 
Give one sum only.


In [9]:
df['TotalCharges'].info()

<class 'pandas.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: TotalCharges
Non-Null Count  Dtype
--------------  -----
7043 non-null   str  
dtypes: str(1)
memory usage: 55.2 KB


As we can see that the df['TotalCharges'] is string types first we need to convert this to int to get the some unless it will concatenate the number but first there is another value ' ' an empty string we have to remove it first then go one with our task

In [10]:
df = df.replace('', pd.NA).dropna() # to remvoe the empty string

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce') # string to numeric 

df.TotalCharges.sum() # print

np.float64(16056168.7)

___
#### TASK 6
Convert “Tenure” into an array.


In [11]:
df.tenure.to_numpy()


array([ 1, 34,  2, ..., 11,  4, 66], shape=(7043,))

In [12]:
df.tenure.dtype

dtype('int64')

____
#### TASK 7

Using point 6, calculate max, min, and mean values.


In [13]:
print(df.tenure.max())
print(df.tenure.min())
print(df.tenure.mean().round(2))

72
0
32.37


___
#### TASK 8
What is the average of the monthly charges?


In [14]:
df.MonthlyCharges.mean()

np.float64(64.76169246059918)

___
#### TASK 9
What is the sum of the monthly charges?


In [15]:
df.MonthlyCharges.sum()

np.float64(456116.6)

___
#### TASK 10
Drop the customerID column.


In [16]:
df.drop(columns='customerID',inplace=True)
df.head(2) # to check if it has

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   

  PaperlessBilling     PaymentMethod  MonthlyCharges  TotalCharges Churn  
0              Yes  Electronic check           29.85         29.85    No  
1               No      Mailed check           56.95       1889.50    No

#### TASK 11
Check for null values in each column.


In [17]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

___
#### TASK 12
Calculate the mean value for the “Tenure” column.


In [18]:
df.tenure.mean()

np.float64(32.37114865824223)

___
#### TASK 13

Count the number of items in the “InternetService” columns.


In [19]:
# finding the values count 
df.tenure.count()

np.int64(7043)

___
### TASK 14

Display number of unique values in ’area code’ column.

--> Note : The dataset you've provided doesn't have area code there is another dataset with name churn.csv that is avialable online it does have area code so I will be using that


In [20]:
df2 = pd.read_csv("churn (2).csv")

print(f" Total Unique Values : {df2["Area Code"].nunique()}")

df2["Area Code"].unique() # every unique value

 Total Unique Values : 33


array([806, 836, 777, 878, 866, 737, 766, 657, 676, 827, 716, 786, 778,
       788, 787, 736, 686, 876, 858, 877, 776, 797, 707, 677, 727, 758,
       659, 678, 848, 658, 798, 847, 868])

___
#### TASK 15
Select rows with label from 0 to 10 and column name ’total day charge’

In [21]:
df2.loc[0:10,['Day Charge']]

Day Charge
0     7.579174
1     4.226289
2     4.768160
3     2.567642
4     5.908916
5     4.804892
6     3.165082
7     1.950098
8     4.331065
9     5.138669
10    3.805903

___
___





## Part 2 Numpy tasks 

___
___

In [22]:
import numpy as np
array1 = np. random . randint (50 , 100 , size =10) 
array2 = np. random . randint (50 , 100 , size =10)


____
#### TASK 1

Create a numpy array that is the sum of array1 and array2

In [23]:
print(f"1st Array : {array1}")
print(f"1st Array : {array2}")

arrays_sum = np.add(array1,array2)

print(f"Sum of  Arrays : {arrays_sum}")

1st Array : [86 56 96 64 82 76 75 87 70 72]
1st Array : [85 91 95 58 58 56 64 53 99 95]
Sum of  Arrays : [171 147 191 122 140 132 139 140 169 167]


___
#### TASK 2

Create a numpy array that is the dot product of array1 and array2.

In [24]:
dot_product =np.dot(array1, array2)

print(f"Dot product of the arrays : {dot_product}")

Dot product of the arrays : 57431


___
#### TASK 3

Create a numpy array that is the cross product of array1 and array2


In [25]:
import numpy as np
array_1 = np. random . randint (50 , 100 , size =9) 
array_2 = np. random . randint (50 , 100 , size =9)



array_1 = array_1.reshape(-1, 3)
array_2 = array_2.reshape(-1,3)


cross_product = np.cross(array_1,array_2)

print(f"The Cross product of Array 1 and Array 2 : {cross_product}")

The Cross product of Array 1 and Array 2 : [[  907 -3259  1255]
 [-3490   680  1832]
 [-1673 -1194  3042]]


___
#### TASK 4
Create a numpy array that is the element-wise product of array1 and array2

In [26]:
element_wise_product = array1* array2

print(f"Element wise product of array1 and array2 : {element_wise_product}")

Element wise product of array1 and array2 : [7310 5096 9120 3712 4756 4256 4800 4611 6930 6840]


___
#### TASK 5

Create a numpy array that is the transpose of array1

In [27]:
array1_transpose = np.transpose(array1)
print(f"Numpy transpose array : {array1_transpose}")

Numpy transpose array : [86 56 96 64 82 76 75 87 70 72]


___
#### TASK 6
 Add array1 and array2 element-wise.

In [28]:
arrays_add = np.add(array1,array2)

print(f"Elements Wise addition : {arrays_add}")

Elements Wise addition : [171 147 191 122 140 132 139 140 169 167]


___
#### TASK 7

 Subtract array2 from array1 element-wise.

In [29]:
array_sub = np.subtract(array1,array2)

print(f"Subtracted array2 : {array_sub}")

Subtracted array2 : [  1 -35   1   6  24  20  11  34 -29 -23]


___
#### TASK 8
Multiply array1 and array2 element-wise.

In [30]:
arrays_mul = array1 * array2 

print(f"Multiplied element wise arrays : {arrays_mul}")

Multiplied element wise arrays : [7310 5096 9120 3712 4756 4256 4800 4611 6930 6840]


___
#### TASK 9
 Divide array1 by array2 element-wise

In [31]:
arrays_divide  = np.divide(array1 , array2)
print(f"Divided array1 : {arrays_divide}")

Divided array1 : [1.01176471 0.61538462 1.01052632 1.10344828 1.4137931  1.35714286
 1.171875   1.64150943 0.70707071 0.75789474]


____
#### TASK 10

Raise array1 to the power of 2

In [32]:
array1_exp = np.power(array1,2)
print(f"2 power array 1 : {array1_exp}")

2 power array 1 : [7396 3136 9216 4096 6724 5776 5625 7569 4900 5184]


___
#### TASK 11

Take the square root of array2.

In [33]:
array2_sqrt = np.sqrt(array2)
print(f"Square Root of array2 : {array2_sqrt}")

Square Root of array2 : [9.21954446 9.53939201 9.74679434 7.61577311 7.61577311 7.48331477
 8.         7.28010989 9.94987437 9.74679434]


____
### TASK 12

Compute the exponential of array1.

In [34]:
exp_array1 = np.exp(array1)

print(f"Exponential Array 1 : {exp_array1}")

Exponential Array 1 : [2.23524660e+37 2.09165950e+24 4.92345829e+41 6.23514908e+27
 4.09399696e+35 1.01480039e+33 3.73324200e+32 6.07603023e+37
 2.51543867e+30 1.85867175e+31]


___
#### TASK 13

 Compute the natural logarithm of array2.

In [35]:
array2_log = np.log(array2)

print(f"Natural Log of array2 : {array2_log}")

Natural Log of array2 : [4.44265126 4.51085951 4.55387689 4.06044301 4.06044301 4.02535169
 4.15888308 3.97029191 4.59511985 4.55387689]


___
#### TASK 14

 Compute the absolute value of array1.

In [36]:
array1_abs = np.abs(array1)

print(f"Absolute value of array : {array1_abs}")

Absolute value of array : [86 56 96 64 82 76 75 87 70 72]


___
#### TASK 15

Compute the minimum value across all elements in array2

In [37]:
min_array2 = np.min(array2)

print(f"Minimum value of array2 : {min_array2}")

Minimum value of array2 : 53


___