## Ahmad
## 2610 4004

### lab 10
### Programming for AI
### submitted : 8 - 5 - 2026

___
___

In [44]:
import numpy as np

___

1. Create a 1D array of 20 random integers between 1 and 100.


In [45]:
np.random.seed(42)
task1 = np.random.randint(1,100,20)
print(task1)

[52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2]


___

2. Reshape the above array into a 4x5 matrix.

In [46]:
task2 = task1.reshape(4,5)
print(task2)

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]]


___

3. Extract the diagonal elements of a 4x4 identity matrix.

In [47]:
identityMatrix = np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


___

4. Create a 2D array of shape (5, 5) with random integers between 0 and 9, and replace all even

In [48]:
task4 = np.random.randint(0,10,size=(5,5))
task4[task4 % 2 ==0] = -1
print(task4)

[[-1 -1  9  5 -1]
 [-1  9 -1 -1  3]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1  1  3]
 [-1  1  9 -1  9]]


___

5. Given two arrays a and b, find the common elements between them.

In [49]:
np.random.seed(34)
a = np.random.randint(1,20,size=(3,3))
b = np.random.randint(10,30,size=(3,3))

common = np.intersect1d(a, b)
print(f"array a \n {a}")

print(f"array b\n {b}")

print(f"\n common in a | b : {common}")




array a 
 [[ 2 11 10]
 [ 5  4  6]
 [12 11 15]]
array b
 [[28 16 15]
 [10 15 29]
 [29 18 18]]

 common in a | b : [10 15]


___

6. Calculate the matrix product of a 3x4 matrix and a 4x2 matrix.

In [50]:
v = np.random.randint(1,20,size=(3,4))
u  = np.random.randint(1,20,size=(4,2))


product = v.dot(u)
print(product)

[[232 455]
 [169 243]
 [128 334]]


___

7. Create a 1D array of 500 random values between 0 and 1.

In [51]:
array = np.random.rand(500)
print(array)

[1.74693159e-01 5.14798052e-01 8.92897538e-01 9.23681067e-01
 8.35978552e-01 4.99657293e-01 8.20963910e-01 9.34388161e-01
 7.94811874e-01 4.61585102e-01 3.52689806e-01 1.08592425e-01
 9.84776533e-01 1.51058273e-01 2.78412129e-01 6.99129544e-01
 6.47702738e-01 2.23536544e-01 8.01848535e-01 5.12112311e-01
 7.86623788e-02 3.41597610e-02 5.66151307e-01 1.49673560e-01
 2.41233021e-01 3.34857271e-02 6.55924436e-01 8.54428034e-01
 1.99753793e-01 8.07052488e-01 7.54464881e-02 6.36034387e-01
 8.30843192e-01 2.91521538e-01 4.75695151e-01 1.74024371e-01
 9.52968165e-01 4.10959514e-02 8.51403478e-01 8.39402166e-01
 9.61240082e-01 9.10233309e-02 9.63309936e-01 1.12117052e-01
 4.44566773e-02 7.44782047e-01 8.65383688e-01 9.35800636e-01
 6.29926935e-01 3.31384025e-01 4.70719998e-01 8.02129298e-01
 9.42804042e-01 1.63825922e-01 6.18682000e-01 2.33267311e-02
 7.87341331e-02 8.60110866e-01 9.71391258e-01 8.92086973e-01
 6.11041022e-01 2.23862900e-01 4.98863203e-01 9.71354859e-01
 1.87606197e-01 7.827403

___

8. Generate a 10x10 identity matrix.

In [52]:
tenidentity = np.eye(10)
print(tenidentity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


___
9. Use numpy to shuffle the rows randomly in above task.

In [55]:
np.random.shuffle(tenidentity)

print(tenidentity)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


___
10. Generate an array of 10 random integers between 50 and 150 using Numpy. Find the minimum,

maximum, and the sum of the elements in the array.

In [58]:
array = np.random.randint(50,150,size=(10))

print(f"\nArray: {array}")
print(f"\nMinimun value : {array.min()}")
print(f"Maximum value : {array.max()}")
print(f"Sum of the array : {array.sum()}")


Array: [115  84  87 115 123 128  99  72 147  78]

Minimun value : 72
Maximum value : 147
Sum of the array : 1048


___