1. Create a 1D array of 20 random integers between 1 and 100.

2. Reshape the above array into a 4x5 matrix.

3. Extract the diagonal elements of a 4x4 identity matrix.

4. Create a 2D array of shape (5, 5) with random integers between 0 and 9, and replace all even

values with -1.

5. Given two arrays a and b, find the common elements between them.

6. Calculate the matrix product of a 3x4 matrix and a 4x2 matrix.

7. Create a 1D array of 500 random values between 0 and 1.

8. Generate a 10x10 identity matrix.

9. Use numpy to shuffle the rows randomly in above task.

10. Generate an array of 10 random integers between 50 and 150 using Numpy. Find the minimum,

maximum, and the sum of the elements in the array.

In [ ]:
# 1
import numpy as np

matrix = np.random.randint(1,100,20,size=())

print(matrix)

[68 91 47 31 85 98 85 82 76 24 57 24 91 15 29 48 20 30 86 80]


In [3]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [6]:
a = np.arange(0,10,2)
b = np.arange(11,21,2)

c = np.concatenate([a,b])

print(c)

[ 0  2  4  6  8 11 13 15 17 19]


In [11]:
za = np.zeros((2,2,3))
aaa = np.zeros_like((2,2,3))
print(aaa)

[0 0 0]
